### ISSUE TITLE
artifact occurs when using rgb format

### ISSUE THREAD

**Issue by soldivelot** [AmusementClub/vs-nlm-ispc#1]
clip format: `vs.RGB24`

parameter: `core.nlm_ispc.NLMeans(clip,d=0,a=2,s=4,h=1.2)`

![process 00](https://user-images.githubusercontent.com/84898012/162558935-072fe031-cd37-4340-b023-afd6a2d35479.png)

**Comment by WolframRhodium** [comment]
Thanks. I'll look into it.

**Comment by WolframRhodium** [comment]
Please check the latest release.

**Comment by soldivelot** [comment]
solved, thanks.
