### ISSUE TITLE
Can add VapourSynth R45 api3.5 support?

### ISSUE THREAD

**Issue by Ken1256** [AmusementClub/vs-nlm-ispc#5]

**Comment by WolframRhodium** [comment]
It has already used vs api3.

**Comment by Ken1256** [comment]
vapoursynth.Error: Core only supports API R3.5 but the loaded plugin requires API R3.6; Filename: C:\Program Files (x86)\VapourSynth\vsnlm_ispc.dll; Name: Non-local means denoise filter implemented in ISPC

I missed.
It should be VapourSynth R45 3.5 api.

**Comment by AkarinVS** [comment]
R42 is way too old, released in 2018. I'm afraid you will have to upgrade your VS version (at least R47 for the getCoreInfo2 API).

**Comment by Ken1256** [comment]
R45 is the most stable in my experience.
I was used to use knlm.KNLMeansCL, but it doesn't support a second GPU or CPU in the system.
```
core.knlm.KNLMeansCL(pp, d=1, a=2, s=4, h=1.2, channels='AUTO', wmode=0, wref=1.0, rclip=None, device_type='gpu', device_id=1)

core.knlm.KNLMeansCL(pp, d=1, a=2, s=4, h=1.2, channels='AUTO', wmode=0, wref=1.0, rclip=None, device_type='cpu')

vapoursynth.Error: knlm.KNLMeansCL: no compatible opencl platforms available!
```

**Comment by AkarinVS** [comment]
Please try this build https://github.com/AmusementClub/vs-nlm-ispc/actions/runs/3112582728.

Please note that in general we don't backport our filters to older VS versions (i.e. we definitely won't backport the [vs-mlrt](https://github.com/AmusementClub/vs-mlrt) filters.)
